### PR TITLE
Fix build failure with Carthage

### PR DESCRIPTION
**Pull request by ikesyo**
Not to use “Parallelize Build” and “Find Implicit Dependencies”.

Fixes https://github.com/ReactiveKit/ReactiveKit/issues/18.

### CODE REVIEW

**Comment by toshi0383** [comment]
Hmm your branch fails to build in my workspace... Any ideas ?
`carthage build --no-skip-current --platform tvos` works fine.
`carthage build --no-skip-current` fails .

```
$ carthage build --no-skip-current 
*** xcodebuild output can be found in /var/folders/tr/3lftss053tqdh731cgt0w1p00000gn/T/carthage-xcodebuild.CTv6h4.log
*** Building scheme "ReactiveFoundation-tvOS" in ReactiveFoundation.xcworkspace
2015-12-24 10:37:11.745 xcodebuild[99866:1893704] ### Failed to load Addressbook class CNContactNameFormatter
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal arm64 /Users/toshi0383/github/ikesyoReactiveFoundation/ReactiveFoundation/ReactiveNSObject.swift
    CompileSwift normal arm64 /Users/toshi0383/github/ikesyoReactiveFoundation/ReactiveFoundation/RKKeyValueObservable.swift
    CompileSwift normal arm64 /Users/toshi0383/github/ikesyoReactiveFoundation/ReactiveFoundation/ReactiveNSNotificationCenter.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(4 failures)
/Users/toshi0383/github/ikesyoReactiveFoundation/ReactiveFoundation/ReactiveNSObject.swift:25:8: error: module file's minimum deployment target is tvos9.1 v9.1: /Users/toshi0383/Library/Developer/Xcode/DerivedData/ReactiveFoundation-btkzlyphhsrpncbtydkkjxvzllqt/Build/Products/Release-appletvos/ReactiveKit.framework/Modules/ReactiveKit.swiftmodule/arm64.swiftmodule
/Users/toshi0383/github/ikesyoReactiveFoundation/ReactiveFoundation/ReactiveNSObject.swift:25:8: error: module file's minimum deployment target is tvos9.1 v9.1: /Users/toshi0383/Library/Developer/Xcode/DerivedData/ReactiveFoundation-btkzlyphhsrpncbtydkkjxvzllqt/Build/Products/Release-appletvos/ReactiveKit.framework/Modules/ReactiveKit.swiftmodule/arm64.swiftmodule
/Users/toshi0383/github/ikesyoReactiveFoundation/ReactiveFoundation/ReactiveNSObject.swift:25:8: error: module file's minimum deployment target is tvos9.1 v9.1: /Users/toshi0383/Library/Developer/Xcode/DerivedData/ReactiveFoundation-btkzlyphhsrpncbtydkkjxvzllqt/Build/Products/Release-appletvos/ReactiveKit.framework/Modules/ReactiveKit.swiftmodule/arm64.swiftmodule
A shell task failed with exit code 65:
2015-12-24 10:37:11.745 xcodebuild[99866:1893704] ### Failed to load Addressbook class CNContactNameFormatter
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal arm64 /Users/toshi0383/github/ikesyoReactiveFoundation/ReactiveFoundation/ReactiveNSObject.swift
    CompileSwift normal arm64 /Users/toshi0383/github/ikesyoReactiveFoundation/ReactiveFoundation/RKKeyValueObservable.swift
    CompileSwift normal arm64 /Users/toshi0383/github/ikesyoReactiveFoundation/ReactiveFoundation/ReactiveNSNotificationCenter.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(4 failures)
```

```
$ carthage version 
0.11.0
$ xcodebuild -version
Xcode 7.2
Build version 7C68
$  swift --version
Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin15.0.0
```

**Comment by ikesyo** [comment]
I succeeded to build with `carthage build --no-skip-current`. How about if you remove `ReactiveKit-*` and `ReactiveFoundation-*` from your derived data dir?

**Comment by toshi0383** [comment]
Removing derived data did not work for me.
Never mind, maybe I should reinstall Xcode or even OSX ...

**Comment by toshi0383** [comment]
My bad. I was on wrong branch.
Switched to the branch `fix-carthage-build` , removed all derived data, and still got this error.

`target 'ReactiveKit-watchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform`

**Comment by ikesyo** [comment]
That seems to be the same as https://github.com/Carthage/Carthage/issues/685 and https://github.com/Carthage/Carthage/issues/716. Do you have valid watchOS simulators?

**Comment by srdanrasic** [comment]
@ikesyo, thank you for fixing this, it's much appreciated!

**Comment by toshi0383** [comment]
@ikesyo  Resetting simulators solved my issue. thanks a lot !!!

**Comment by ikesyo** [comment]
:smile:

**Pull request merged**
